### ISSUE TITLE
Error while reading from ASTEC

### ISSUE THREAD

**Issue by stefanhahmann** [leoguignard/LineageTree#14]
I would like to read data from an ASTEC file. I am using the file extracted from this resource: https://figshare.com/articles/dataset/Astec-U0126-Pm1_U0126_treated_Phallusia_mammillata_embryo_live_SPIM_imaging_stages_5-13_/11307431?file=20040497

```
import lineageTree

def load_pkl():
    tree = lineageTree.lineageTree()
    tree.read_from_ASTEC(file_path="Astec-U0126-Pm1_properties.pkl", eigen=True)

if __name__ == '__main__':
    load_pkl()

```

When executing this script, I receive the following error message:

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.2.1\plugins\python\helpers\pydev\pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm 2023.2.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\s\git\LineageTree\src\LineageTree\load_pkl.py", line 15, in <module>
    load_pkl()
  File "C:\Users\s\git\LineageTree\src\LineageTree\load_pkl.py", line 7, in load_pkl
    tree.read_from_ASTEC(file_path="Astec-U0126-Pm1_properties.pkl", eigen=True)
  File "C:\Users\s\git\LineageTree\src\LineageTree\lineageTree.py", line 934, in read_from_ASTEC
    lt = tmp_data["cell_lineage"]
         ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'cell_lineage'
```

**Comment by leoguignard** [comment]
That being said, there might be a specific reason why you are reading the dataset the way you are showing but I personally would do it that way:

```python
from LineageTree import lineageTree

path_to_pkl = "your/path/to.pkl"
tree = lineageTree(path_to_pkl, file_type="ASTEC")
```

It should give the exact same result but it is more concise ...

**Comment by stefanhahmann** [comment]
Thanks for the hints. I understand that the error is more about the data than about the code. Thus, I am closing the issue.
